<html>
	<head>
		<title>注册成为新用户</title>
	</head>
	<body>
		<form action="/fund/login/register" method="post">
			username:<input type="text" name="username" length=20/>
			password:<input type="password" name="password1" length=20/>
			password:<input type="password" name="password2" length=20/>
			basicincome:<input type="text" name="basic_income" length=20/>
			palnsave:<input type="text" name="plan_save" length=20/>
			tofamily:<input type="text" name="to_family" length=20/>
			rent:<input type="text" name="rent" length=20/>
			<input type="submit" value="提交"/>
		</form>
	</body>
</html>
