<html>
	<head>
		<title>添加收支信息</title>
		<script type="text/javascript"> 
			function doAction(index){ 
				var arr = new Array; 
				arr[0] = [ new Option('--收支明细--', '-1',true) ]; 
				arr[1] = [  new Option('工资', 'income1',true), 
						    new Option('奖金', 'income2'), 
							new Option('理财', 'income3'), 
							new Option('其他', 'income4') ]; 
				arr[2] = [  new Option('房租', 'consume1',true), 
						    new Option('定存', 'consume2'), 
						    new Option('餐费', 'consume3'), 
						    new Option('水电', 'consume4'), 
						    new Option('购物', 'consume5'), 
						    new Option('充电', 'consume6'), 
						    new Option('孝敬父母', 'consume7'), 
						    new Option('其他', 'consume8') ]; 
				var briefreason = document.getElementById('briefreason');
				briefreason.innerHTML = ''; 
				for (i = 0;i<arr[index].length; i++){ 
					briefreason.options[i] = arr[index][i]; 
				}
			}
			window.onload = function(){
				var index = document.getElementById('type').value;
				index = parseInt(index) + 1;
				doAction(index);
			}
		</script>
	</head>
	<body>
		<form action="/fund/account/add" method="post">
			收支类型:
			<select id="type" name="type" onchange="doAction(this.selectedIndex);"> 
				<option value="-1" selected>--收支类型--</option> 
				<option value="0">----收入----</option> 
				<option value="1">----支出----</option> 
			</select>
			收支明细:
			<select name="briefreason" id="briefreason"> 
				<option value="-1" selected>--收支明细--</option> 
			</select> 
			收支来源:
			<select name="source" id="source"> 
				<option value="-1" selected>--收支来源--</option> 
				<option value="card">--银行卡--</option> 
				<option value="cash">--现金--</option> 
				<option value="online">--在线支付--</option> 
			</select>
			费用:<input type="text" length='20' name='cost'/><br/>
			详细:<textarea row="40" col="40" name='remarks'></textarea>
			<input type="submit" value="添加" /> 
		</form> 
	</body>
</html>
